name: MiningServerPlugin
version: '1.0-SNAPSHOT'
main: icewizard7.miningServerPlugin.MiningServerPlugin
api-version: '1.21'
authors: [ IceWizard7 ]

commands:
  info:
    description: Get information about this plugin
    permission: miningServerPlugin.info
    usage: /info
  god:
    description: Makes you invulnerable
    permission: miningServerPlugin.god
    usage: /god
  fly:
    description: Makes you fly
    permission: miningServerPlugin.fly
    usage: /fly
  vanish:
    description: Makes you invisible
    permission: miningServerPlugin.vanish
    usage: /vanish
  invsee:
    description: See the inventory of other players
    permission: miningServerPlugin.invsee
    usage: /invsee playerName
  autocompress:
    description: Auto-compresses your items
    permission: miningServerPlugin.autocompress
    usage: /autocompress
    aliases: [ac]

permissions:
  miningServerPlugin.info:
    description: Allows using /info
    default: true
  miningServerPlugin.god:
    description: Allows using /god
    default: op
  miningServerPlugin.fly:
    description: Allows using /fly
    default: op
  miningServerPlugin.vanish:
    description: Allows using /vanish
    default: op
  miningServerPlugin.invsee:
    description: Allows using /invsee
    default: op
  miningServerPlugin.autocompress:
    description: Allows using /autocompress
    default: op
