name: MiningServerPlugin
version: '1.0-SNAPSHOT'
main: icewizard7.miningServerPlugin.MiningServerPlugin
api-version: '1.21'
authors: [ IceWizard7 ]

commands:
  info:
    description: Get information about this plugin
    permission: miningServerPlugin.info
    usage: /info
  god:
    description: Makes you invulnerable
    permission: miningServerPlugin.god
    usage: /god
  fly:
    description: Makes you fly
    permission: miningServerPlugin.fly
    usage: /fly
  vanish:
    description: Makes you invisible
    permission: miningServerPlugin.vanish
    usage: /vanish
  invsee:
    description: See the inventory of other players
    permission: miningServerPlugin.invsee
    usage: /invsee <player>
  autocompress:
    description: Auto-compresses your items
    permission: miningServerPlugin.autocompress
    usage: /autocompress
    aliases: [ac]
  warp:
    description: Teleport anywhere
    permission: miningServerPlugin.warp
    usage: /warp <location>
  spawn:
    description: Teleport to spawn
    permission: miningServerPlugin.spawn
    usage: /spawn
  voucher:
    description: Create vouchers
    permission: miningServerPlugin.voucher.create
    usage: /voucher create <role>

permissions:
  miningServerPlugin.info:
    description: Allows using /info
    default: true
  miningServerPlugin.god:
    description: Allows using /god
    default: op
  miningServerPlugin.fly:
    description: Allows using /fly
    default: op
  miningServerPlugin.vanish:
    description: Allows using /vanish
    default: op
  miningServerPlugin.invsee:
    description: Allows using /invsee
    default: op
  miningServerPlugin.autocompress:
    description: Allows using /autocompress
    default: op
  miningServerPlugin.warp:
    description: Allows using /warp
    default: op
    children:
      miningServerPlugin.warp.oak: true
      miningServerPlugin.warp.stone: true
      miningServerPlugin.warp.copper: true
      miningServerPlugin.warp.coal: true
      miningServerPlugin.warp.iron: true
      miningServerPlugin.warp.gold: true
      miningServerPlugin.warp.diamond: true
      miningServerPlugin.warp.emerald: true
      miningServerPlugin.warp.netherite: true
      miningServerPlugin.warp.blackstone: true
      miningServerPlugin.warp.quartz: true
      miningServerPlugin.warp.admin: true

  miningServerPlugin.warp.oak:
    description: Allows warping to Oak
    default: false
  miningServerPlugin.warp.stone:
    description: Allows warping to Stone
    default: false
  miningServerPlugin.warp.copper:
    description: Allows warping to Copper
    default: false
  miningServerPlugin.warp.coal:
    description: Allows warping to Coal
    default: false
  miningServerPlugin.warp.iron:
    description: Allows warping to Iron
    default: false
  miningServerPlugin.warp.gold:
    description: Allows warping to Gold
    default: false
  miningServerPlugin.warp.diamond:
    description: Allows warping to Diamond
    default: false
  miningServerPlugin.warp.emerald:
    description: Allows warping to Emerald
    default: false
  miningServerPlugin.warp.netherite:
    description: Allows warping to Netherite
    default: false
  miningServerPlugin.warp.blackstone:
    description: Allows warping to Blackstone
    default: false
  miningServerPlugin.warp.quartz:
    description: Allows warping to Quartz
    default: false
  miningServerPlugin.warp.admin:
    description: Allows warping to Admin
    default: false
  miningServerPlugin.spawn:
    description: Allows using /spawn
    default: op
  miningServerPlugin.voucher.create:
    description: Allows using /voucher create
    default: op
